name: Resturant Manager CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.27.1'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APKs
        run: flutter build apk --split-per-abi
      - name: Create APKs directory (if not exists)
        run: mkdir -p apks
      
      - name: Copy APKs to directory
        run: cp build/app/outputs/apk/release/*.apk apks/

      - name: Configure Git
        run: |
          git config --global user.name "Ah95ed"
          git config --global user.email "Amhmeed31@gmail.com"

      - name: Commit and Push APKs
        run: |
          git add apks/*.apk
          git commit -m "ci: Update APK files [skip ci]"
          git push origin HEAD:main

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-apks
          path: build/app/outputs/apk/release/*.apk